#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
rm -rf VTK
rm -rf constant/cellToRegion constant/polyMesh/sets
rm -f 0/cellToRegion
rm -rf constant/fuel/polyMesh
rm -rf constant/cladding/polyMesh
rm -rf constant/coolant/polyMesh
rm -rf postProcessing

# ----------------------------------------------------------------- end-of-file
