#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory


# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

#-- Run on single processor
#runApplication `getApplication`
thesisCoupledFoam

## Decompose
#runApplication decomposePar -allRegions

## Run
#runParallel `getApplication` 8

## Reconstruct
#runApplication reconstructPar -allRegions

echo
echo "creating files for paraview post-processing"
echo
paraFoam -touchAll

# ----------------------------------------------------------------- end-of-file
