#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory


# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
#gmshToFoam ../meshes/4asec.msh
runApplication topoSet
runApplication splitMeshRegions -cellZones -overwrite

# remove fluid fields from solid regions (important for post-processing)
for i in fuel cladding gap
do
   rm -f 0*/$i/{mut,alphat,epsilon,k,U,p_rgh}
done

for i in cooler cladding gap fuel
do
   changeDictionary -region $i > log.changeDictionary.$i 2>&1
done


#-- Run on single processor
#runApplication `getApplication`
#ddd chtMultiRegionSimpleFoam

#
## Decompose
runApplication decomposePar -allRegions

## Run
runParallel `getApplication` 8

## Reconstruct
runApplication reconstructPar -allRegions

echo
echo "creating files for paraview post-processing"
echo
paraFoam -touchAll

# ----------------------------------------------------------------- end-of-file
