#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

#gmshToFoam malha/subcanal.msh
gmshToFoam ../malhas/celula.msh

# Mudar em constant/polyMesh/boundary
# as condições da parede de *patch* para *symmetry*

cp constant/polyMesh/boundary.symmetry constant/polyMesh/boundary
# -cellZones era o anterior para a malha boa3dtheler

runApplication splitMeshRegions -cellZonesOnly -overwrite 

# remove fluid fields from solid regions (important for post-processing)
for i in fuel cladding
do
   rm -f 0*/$i/{mut,alphat,epsilon,k,U,p_rgh}
done

for i in coolant cladding fuel
do
   changeDictionary -region $i > log.changeDictionary.$i 2>&1
done

